#!/bin/bash

set -e

cat > /etc/ecs/ecs.config << EOM
ECS_CLUSTER=${cluster_name}
ECS_LOGLEVEL=debug
ECS_AVAILABLE_LOGGING_DRIVERS=["json-file","awslogs"]
EOM

yum install -y awslogs

cat > /etc/awslogs/awslogs.conf.tmp << EOM
[general]
state_file = /var/lib/awslogs/agent-state

[/var/log/docker]
file = /var/log/docker
log_group_name = uscis-docker
log_stream_name = {cluster}/{container_instance_id}
datetime_format = %Y-%m-%dT%H:%M:%S.%f

[/var/log/ecs/ecs-init.log]
file = /var/log/ecs/ecs-init.log
log_group_name = uscis-ecs-init.log
log_stream_name = {cluster}/{container_instance_id}
datetime_format = %Y-%m-%dT%H:%M:%SZ

[/var/log/ecs/ecs-agent.log]
file = /var/log/ecs/ecs-agent.log.*
log_group_name = uscis-ecs-agent.log
log_stream_name = {cluster}/{container_instance_id}
datetime_format = %Y-%m-%dT%H:%M:%SZ
EOM

if [ -f /etc/awslogs/awslogs.conf ]
then
  mv /etc/awslogs/awslogs.conf /etc/awslogs/awslogs.conf.bak
fi

mv /etc/awslogs/awslogs.conf.tmp /etc/awslogs/awslogs.conf

curl -s -L -o /usr/local/bin/jq \
  "https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64"

chmod +x /usr/local/bin/jq

cluster=$(curl -s http://localhost:51678/v1/metadata | \
  /usr/local/bin/jq -r '. | .Cluster'
)
sed -i -e "s/{cluster}/$cluster/g" /etc/awslogs/awslogs.conf

container_instance_id=$(curl -s http://localhost:51678/v1/metadata | \
  /usr/local/bin/jq -r '. | .ContainerInstanceArn' | \
  awk -F/ '{print $2}'
)
sed -i -e "s/{container_instance_id}/$container_instance_id/g" /etc/awslogs/awslogs.conf

service awslogs start
