version: '3'
services:
  db:
    image: postgres
  backend:
    build: backend
    # https://stackoverflow.com/a/38732187/42559
    entrypoint: /myapp/entrypoint.sh
    command: bundle exec rails s -p 3001 -b '0.0.0.0'
    volumes:
      - ./backend/:/myapp
    ports:
      - "3001:3001"
    depends_on:
      - db
    env_file:
      - ./.env
  frontend:
    build: frontend
    command: yarn start
    volumes:
      - ./frontend/:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
